# Generated by Django 5.1.1 on 2024-10-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_alter_cartitem_product"),
        ("inventory", "0001_initial"),
        ("logistics", "0002_alter_shipment_product"),
        ("orders", "0003_alter_orderitem_product"),
        ("products", "0001_initial"),
        ("sales_analytics", "0002_alter_salesbyproduct_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=None,
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_records",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransfer",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_handled",
                to="products.product",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
