# Generated by Django 5.1.1 on 2024-09-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('destination', models.CharField(max_length=255)),
                ('shipped_date', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField()),
                ('tracking_number', models.CharField(max_length=255, unique=True)),
                ('shipping_company', models.CharField(default='DHL', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In_transit'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_shipments', to='inventory.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-shipped_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_transit', 'In Transit'), ('received', 'Received'), ('refunded', 'Refunded')], default='initiated', max_length=50)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Return Shipment',
                'verbose_name_plural': 'Return Shipments',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivered', 'Delivered'), ('delay', 'Delay'), ('customs', 'Customs Clearance')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_interactions', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Logistics Interaction',
                'verbose_name_plural': 'Logistics Interactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
