# Generated by Django 5.1.1 on 2024-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logisticsinteraction",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Logistics Interaction",
                "verbose_name_plural": "Logistics Interactions",
            },
        ),
        migrations.AlterModelOptions(
            name="returnshipment",
            options={
                "ordering": ["-received_at"],
                "verbose_name": "Return Shipment",
                "verbose_name_plural": "Return Shipments",
            },
        ),
        migrations.AlterModelOptions(
            name="shipment",
            options={
                "ordering": ["-shipped_date"],
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
            },
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_transit", "In_transit"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
