# Generated by Django 5.1.1 on 2024-10-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
