# Generated by Django 5.1.1 on 2024-09-23 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={
                "ordering": ["-last_updated"],
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
            },
        ),
        migrations.AlterModelOptions(
            name="inventorytransfer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Inventory Transfer",
                "verbose_name_plural": "Inventory Transfers",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="stockadjustment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Stock Adjustment",
                "verbose_name_plural": "Stock Adjustments",
            },
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "ordering": ["name"],
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
            },
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("product", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("name", "sku")},
        ),
    ]
