# Generated by Django 5.1.1 on 2024-09-23 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0004_alter_address_unique_together_customer_unique_email_and_more",
        ),
        ("orders", "0002_cart_cartcoupon_carthistory_cartitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="carthistory",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="customers.customer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartcoupon",
            unique_together={("cart", "code")},
        ),
    ]
