# Generated by Django 5.1.1 on 2024-09-23 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0003_cart_session_key_carthistory_notes_cartitem_added_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
