# Generated by Django 5.1.1 on 2024-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_cartitem_added_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
