# Generated by Django 5.1.1 on 2024-10-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_brand_rename_price_product_base_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="sku",
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_brands",
                to="products.brand",
            ),
        ),
    ]
