# Generated by Django 5.1.1 on 2024-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_productvariant_sku_product_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
