# Generated by Django 5.1.1 on 2024-10-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productvariant_sku_alter_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
