# Generated by Django 5.1.1 on 2024-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0002_alter_category_options_alter_inventoryitem_options_and_more",
        ),
        ("sales_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesbycustomersegment",
            options={
                "ordering": ["segment"],
                "verbose_name": "Sales by Customer Segment",
                "verbose_name_plural": "Sales by Customer Segments",
            },
        ),
        migrations.AlterModelOptions(
            name="salesbyproduct",
            options={
                "ordering": ["-total_units_sold"],
                "verbose_name": "Sales by Product",
                "verbose_name_plural": "Sales by Product",
            },
        ),
        migrations.AlterModelOptions(
            name="salesreport",
            options={
                "ordering": ["-report_date"],
                "verbose_name": "Sales Report",
                "verbose_name_plural": "Sales Reports",
            },
        ),
        migrations.AddIndex(
            model_name="salesreport",
            index=models.Index(
                fields=["report_date"], name="sales_analy_report__93510e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesbycustomersegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_sales__gte", 0)),
                name="total_sales_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesbycustomersegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_orders__gte", 0)),
                name="total_orders_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesbyproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_units_sold__gte", 0)),
                name="total_units_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesbyproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_revenue__gte", 0)),
                name="total_revenue_non_negative",
            ),
        ),
    ]
