# Generated by Django 5.1.1 on 2024-10-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='products.product'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='highest_selling_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_selling_product', to='products.product'),
        ),
    ]
